// <auto-generated />
using Epiroc.Data.Entity.DBSets;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Epiroc.Data.Entity.Migrations.ProjectDetail
{
    [DbContext(typeof(ProjectDetailContext))]
    [Migration("20220131013205_Migration1")]
    partial class Migration1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Epiroc.Data.Entity.ProjectDetail", b =>
                {
                    b.Property<int>("ProjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Department")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectCost")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectHr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProjectId");

                    b.ToTable("ProjectDetails");

                    b.HasData(
                        new
                        {
                            ProjectId = 1,
                            Department = "Construction",
                            ProjectCost = "250",
                            ProjectHr = "10hr",
                            ProjectName = "abc"
                        },
                        new
                        {
                            ProjectId = 2,
                            Department = "Construction",
                            ProjectCost = "250",
                            ProjectHr = "10hr",
                            ProjectName = "abc"
                        },
                        new
                        {
                            ProjectId = 3,
                            Department = "water-Energy",
                            ProjectCost = "250",
                            ProjectHr = "10hr",
                            ProjectName = "abc"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
